### ISSUE TITLE
Can Each Source Be Trained Separately? - Unable to Train Quality Model

### ISSUE THREAD

**Issue by Anjok07** [facebookresearch/demucs#300]
## ❓ Questions

@adefossez 

Thank you for your help in https://github.com/facebookresearch/demucs/issues/221 !

I'm running into a new problem. 

I was able to get training started by using the following dset settings:

```
dset:
  wav: C:/Users/Anjok/Desktop/Demucs-Train/test <------ Dataset location
  sources: ['vocals', 'non_vocals']
  samplerate: 44100
  channels: 2
epochs: 320
batch_size: 6 <--------- I'm using an RTX 3090 with 24GB's of V-RAM. This was the largest batch size I was able to use.
weights: [1.,1.] <--------- I had to decrease the number of weights from 4 to 2.
```

I was able to train a model, but it comes out very poorly and with much distortion. The dataset consists of 1400 tracks and I've been able to successfully train a strong vocal model that achieved a 9.703 SDR on AIcrowds testset using the [KUIELAB-MDX-Net](https://github.com/kuielab/mdx-net-submission) code, so I know there isn't an issue with the dataset. I'm wondering if having to decrease the number of weights is causing this issue? I also tried training with the vocal stem and mixture only using the following settings, but the results were even worse.

```
dset:
  wav: C:/Users/Anjok/Desktop/Demucs-Train/test
  sources: ['vocals']
  samplerate: 44100
  channels: 2
epochs: 320
batch_size: 6 
weights: [1.] <--------- Decreased the number of weights from 2 to 1.
```

I'm eager to train Demucs using our dataset because I know it's solid, but I can't seem to get a good model yet. What would you recommend?

**Comment by adefossez** [comment]
the number of weights is just the weighting for the loss terms, i.e. how much the model will focus on each source. you indeed have to decrease it to have the same size as sources. so the folder `C:/Users/Anjok/Desktop/Demucs-Train/test` does contain both the train and valid ? maybe you would have a training log i could look at ? (it should be inside the experiment folder, based on the experiment signature). if it is sensitive, feel free to send it by email, defossez at fb dot com.

The second option is not valid due to the ways things are implemented, at train time I dont load the mixture, and regenerate it from the sources, so if there is a single source, the input and output of the model are the same.

can you try deactivating the pitch augmentation ? `augment.repitch.proba=0`. alternatively you can change https://github.com/facebookresearch/demucs/blob/main/demucs/repitch.py#L23 replace `[3]` with `[1]`.

**Comment by Anjok07** [comment]
Thank you for the response!

I think I figured out the issue! I was training on the non-hybrid version of the model. Now that I'm training with the Hybrid version, it's progressing much better now. 

Here are the exact settings I'm using:

```
dset:
  wav: C:/Users/Anjok/Desktop/Demucs-Train/OriginalDataset-train
  samplerate: 44100
  channels: 2
  sources: ['vocals', 'non_vocals']
epochs: 320
batch_size: 6
weights: [1.,1.]

model: hdemucs

augment:
  shift_same: false
  repitch:
    proba: 0
    max_tempo: 0
  remix:
    proba: 0
    group_size: 0
  scale:
    proba: 0
    min: 0
    max: 0
  flip: false
```

I let a model train overnight using the **full UVR dataset** and the results were stunning after just 1 epoch! 

To answer your questions:

_Does contain both the train and valid?_ Yes, I have a train and valid directories.
_can you try deactivating the pitch augmentation?_ I've actually had this disabled the whole time.
